### ISSUE TITLE
Strange Behavior Near Vertical Asymptotes

### ISSUE THREAD

**Issue by fny** [mauriciopoppe/function-plot#101]
Instead of proper verticals on the curves, lines end up being drawn from the origin to wherever the curve is being draw from the start:

<img width="482" alt="screen shot 2017-09-21 at 5 11 37 pm" src="https://user-images.githubusercontent.com/346068/30719099-3de519c8-9ef0-11e7-8726-93efb4df7799.png">

<img width="520" alt="screen shot 2017-09-21 at 5 11 52 pm" src="https://user-images.githubusercontent.com/346068/30719102-40dc17ee-9ef0-11e7-8bb9-8a10dedf1a66.png">

<img width="555" alt="screen shot 2017-09-21 at 5 12 00 pm" src="https://user-images.githubusercontent.com/346068/30719105-440105b0-9ef0-11e7-9e17-ae7cc098d3cd.png">

Move ⍴ upwards in this example to see the effect:
https://output.jsbin.com/roruha/21

**Comment by mauriciopoppe** [comment]
this is because the evaluator uses same spaced samples from the visible range and unfortunately this doesn't work on your case because the values grow way too fast near a point for the evaluator to catch up, I'd suggest that you rewrite your functions using interval arithmetic instead

**Comment by fny** [comment]
Will definitely look into creating an evaluator. As for interval arithmetic, can you provide some guidance on how to handle fractional powers?

Also, thank you so much for these invaluable math libraries!

**Comment by mauriciopoppe** [comment]
For interval arithmetic use https://mauriciopoppe.github.io/interval-arithmetic/0.6.8/Interval.html#nthRoot, there's also an example on the homepage that shows how to use it (look for nth-root)
