### ISSUE TITLE
Altering the location of the Axis numbers

### ISSUE THREAD

**Issue by szaske** [mauriciopoppe/function-plot#103]
I'd like to make changes to the Function-plot.  I want to make changes to the visuals:

1. Put the axis numbers next to the lines you call the "Y origin" and "X origin", and have them stay there when the graph is zoomed or panned.
2. Put arrow ends on the Origin lines

I'm a junior developer and this will be my first attempt at altering someone else's code.  Are you willing to accept pull requests if I make these changes?  Any suggestions on how I should proceed, so my alterations could be accepted?  I'm a bit nervous to fork the full package, since that would mean I won't get any future changes you might make.  Thanks.

**Comment by mauriciopoppe** [comment]
Thank you for your interest in contributing to this library, I'm actually considering into rewriting most of the library to split it into several modules, therefore I'm not sure if this is the correct repo to contribute at this moment because it's gonna be rewritten anyways.

Your ideas are very valuable though, I'll consider them when I get to do the rewrite.

**Comment by szaske** [comment]
Thank you Mauricio, for the quick response.  I'm working on Function Plot
as an Intern project, so I'd still like to make the changes, even if you
don't accept them.  I'm hoping you might give me a little bit of help
understanding your code as a junior dev like myself knows when to ask for
help :).  I've install Function-Plot and have the playground working.  I'm
not familiar with D3 unfortunately...so I'm trying to both understand how
it works while also trying to understand how you've coded Function-Plot

D3 seems at first blush to be like a charting-centered version of jQuery.
You can select elements and then alter them.  I'm slowing learning how it
works.

After a day and a half looking through the code here's what I've found so
far:

1. Your x.axis and y.axis items are what I want to alter.  I was quickly
able to get them in the right location after the chart is drawn, but
unfortunately that only put them in the center of the chart, and breaks
when the user mouse moved or zoom in.
2. Your x and y.origin lines 'float' exactly where I want the x/y.axis
items to be, so my first thought is to either put those elements as
children of x/y.origin or have them mirror the same transforms.
3. I see that the tick items have a transform attribute, but I cannot
figure out where you're setting that in the code or how you're altering it
when a user drags the mouse.  I would expect to see some sort of mousedrag
event listener, but I haven't been able to find one yet.
4. The x.axis does properly slide left to right with the mouse movements,
but I also need it to slide on the y axis, so I believe what I need to do
it get that transform to accept y axis transforms as well.

So my question to you is, can you tell me where you're setting these
transforms on the axis items?  I'd appreciate and insights you can give
me,  -=Steve

**Comment by mauriciopoppe** [comment]
Sure, every time you zoom or pan on the graph the following callback is called: https://github.com/mauriciopoppe/function-plot/blob/74e8e2611e2ee8dcb57886163898120eec40f74e/lib/index.js#L585-L593, in the call stack this is the place where the lines are updated https://github.com/mauriciopoppe/function-plot/blob/74e8e2611e2ee8dcb57886163898120eec40f74e/lib/index.js#L385-L407, as you see this is following the join/enter/update/exit pattern in d3

For example the line y = 0 (the x axis) is drawn as follows:

```javascript
// join
var xOrigin = content.selectAll(':scope > path.x.origin')
  .data([ [[xScale.domain()[0], 0], [xScale.domain()[1], 0]] ])

// enter
xOrigin.enter()
  .append('path')
  .attr('class', 'x origin')
  .attr('stroke', 'black')
  .attr('opacity', 0.2)
  
// update + enter
xOrigin.attr('d', line)
```

**Comment by szaske** [comment]
Since it sounds like you're considering a re-write, I've decided against making changes to FP code for now and instead I'll list out the requirements I need for a future version of FP if you're interesting in user feature requests.  I understand some of these features are doable today via CSS

1.	The ability to place the xy axis numbers next to the  axis lines, instead of the left and bottom edges.. A labeled, semibold xy axis with arrows pointing off each side
2.	Ability to alter style of the  xy axis lines (thickness, color, opacity)
3.	Ability to alter style of the grid lines (thickness, color, opacity, arrow ends)
4.	Ability to set font size of the Axis numbers (size, color, font)
5.	Ability to set the grid size
6.	I want the power to restrict the domain and/or range of each line (per line, not per graph) using interval notation. If there's a conflict between the two, the more restrictive should apply.  The default should be (- infinity, + infinity), Endpoints visible on the graph should show as bold points or open circles, depending on whether they're [inclusive] or (exclusive).
7.	Ability to customize the step parameters.
8.	When graphing trigonometric functions I want the option to set the step and window parameters to intervals of pi/2 or any multiple thereof. If I do, axis numbers should be written as pi/2, pi, 3pi/2, etc

Thanks for making such a great tool available to us.
