### ISSUE TITLE
ES modules

### ISSUE THREAD

**Issue by lastmjs** [mauriciopoppe/function-plot#104]
I'm having a hard time getting all of the dependencies sorted out with D3 v3 and this library, I think it would be great if function-plot switched to ES modules, since they are standard and will be supported across all major browsers and Node.js, finally one module system and syntax to rule them all! In the meantime, how can I get these dependencies to work? I keep getting:

```
Uncaught TypeError: Cannot read property 'hsl' of undefined
```

I'm trying various ways of doing this. The following does not work:
```
        <script src="https://d3js.org/d3.v3.min.js"></script>
        <script src="https://wzrd.in/standalone/function-plot@1.18.1"></script>

```

Neither does the following:
```
        <script src="https://d3js.org/d3.v3.min.js"></script>
        <script src="../node_modules/function-plot/dist/function-plot.js"></script>
```

Nor the following:
```
        <script src="../node_modules/d3/d3.min.js"></script>
        <script src="../node_modules/function-plot/dist/function-plot.js"></script>
```

**Comment by lastmjs** [comment]
I think the issue is on my side, my suggestion still stands for ES modules, but I'll figure out the dependencies. Thanks!

**Comment by mauriciopoppe** [comment]
Yep, when I created this library d3 wasn't modularized yet and I didn't want to include it as part of the bundle, I think this one will be fixed when I get the chance to rewrite it with d3v4

Try this one https://jsbin.com/yugeqabeyi/1/edit?html,js,output
