### ISSUE TITLE
Shadow DOM

### ISSUE THREAD

**Issue by lastmjs** [mauriciopoppe/function-plot#105]
The `functionPlot` function does not seem to work within a shadow root, rendering it very difficult (impossible at the moment) to use in any kind of application that uses Shadow DOM. I believe the problem is that the `target` option does some kind of document wide query, and thus does not penetrate any shadow roots. Is there any way of passing in the DOM node to `target`, or somehow rendering to a DOM node in memory that I can then attach wherever I would like? This is fully blocking my use of `function-plot` in my application, since I'm using the graphs within multiple layers of shadow roots.

**Comment by lastmjs** [comment]
Looks like it's the d3.select function...

**Comment by lastmjs** [comment]
If `target` could be a DOM node, then you could use the [d3.select(node)](https://github.com/d3/d3-3.x-api-reference/blob/master/Selections.md#d3_select), which would be a potentially simple fix.

**Comment by mauriciopoppe** [comment]
hey @lastmjs, I've taken a quick look at the code and it's doing exactly that:

https://github.com/mauriciopoppe/function-plot/blob/74e8e2611e2ee8dcb57886163898120eec40f74e/lib/index.js#L165

**Comment by lastmjs** [comment]
Just say that too! It seems to be working. If the documentation could explain that `target` can be a string or a DOM node or anything else that d3.select supports, that would be excellent. I can PR if you'd like

**Comment by mauriciopoppe** [comment]
that'd be great thanks!

**Comment by lastmjs** [comment]
Passing in a DOM node is working very well within multiple shadow roots: here's the PR for the documentation update: https://github.com/mauriciopoppe/function-plot/pull/106
