### ISSUE TITLE
Text in annotations problem

### ISSUE THREAD

**Issue by jlfernandez83** [mauriciopoppe/function-plot#109]
Hi all... First of all, thanks for this useful library.

I think I have detected a bug. To reproduce, create a "function plot graphic" with annotations in it. The need to have text. Then, try to change the position in annotations. They will keep the old text, no matter if you change it. Here is the code:

`window.d3 = require('d3');`
`var functionPlot = require('function-plot');`
` `
`opts = {`
`  target: '#the_container',`
`  annotations:[`
`    {x: 0 , text: 'x=0'},`
`   {x: 1 , text: 'x=1'},`
`   {x: 2 , text: 'x=2'},`
` ],`
`  data: [{`
`    fn: 'x^2'`
`  }]`
`};`
`instance = functionPlot(opts)`
`//Here we go with the new options`
`instance.options.annotations = [`
`  {x: 4 , text: 'x=4'},`
`  {x: 5 , text: 'x=5'},`
`  {x: 6 , text: 'x=6'},`
`];`
`instance.draw();`

As you can see, new annotations are created with same old text. Seems like there is a kind of cache mechanism associated with the index of the element in the array...

**Comment by mauriciopoppe** [comment]
Thank you for the report! I'll see what's happening during the weekend

**Comment by jlfernandez83** [comment]
Thanks to yo again. 

The workaround I've come to for the momento is calling an extra `instance.draw()` with an empty array in annotations, and then another one with the annotations I really want. Hope that makes the 'hunting' easier for you.

By the way, if you call `instance.draw()` after changing the grid option, it doesn't gets reflected either. Not sure if it is related...

Let me know if you need further help.

**Comment by jlfernandez83** [comment]
Update: 

Hi again. Not sure if it is related, but this doesn't work well either:

`window.d3 = require('d3');`
`var functionPlot = require('function-plot');`

`opts = {`
  `  target: '#container_id',`
`    grid: false,`
`    data: [{`
`    fn: 'x^2'`
`  },{`
`	fn: 'x',`
`  }]`
`};`

`instance = functionPlot(opts);`
`instance.options.data = [{`
`    fn: 'x^2'`
`  }];`
`instance.draw();`

Old function fn = 'x' remains painted in the canvas, but tip loses it reference. The only workaround I've found so far in this case is to completely remove the canvas element and recreate it.
