### ISSUE TITLE
Installation section on homepage should mention D3 requirement

### ISSUE THREAD

**Issue by Hritik14** [mauriciopoppe/function-plot#111]
The homepage says it's built on the top of D3 but it is not sure if the user has to import it by himself or it is done behind the scenes.

**Comment by FullPint** [comment]
The homepage while not super clear does mention that you do need to include it in your webpage. 


**and include it in your webpage as**
```
<script src="bower_components/d3/d3.min.js"></script>
<script src="bower_components/function-plot/dist/function-plot.js"></script>
```

**Comment by Hritik14** [comment]
It's been a quite a lot of time but I suppose I had problems with the standalone version.
In that case (if I remember correctly) you need to import d3.

**Comment by mauriciopoppe** [comment]
I've updated the website and the README files with instructions on how to install the dependencies with npm as well as the browser
