### ISSUE TITLE
Thickness of graph

### ISSUE THREAD

**Issue by Hritik14** [mauriciopoppe/function-plot#112]
In some situation it feels necessary to thicken a graph (like user hovering over certain stuff related to graph) to highlight it. 
It would be really nice if there could be a 
`{fn: 'x^2', weight: '20px'}`

**Comment by kortina** [comment]
I was able to change thicknesss of a line with:

```
 {
    fn: "x^2",
    attr: { "stroke-width": 3 }
}
```
