### ISSUE TITLE
Using it on observablehq.com

### ISSUE THREAD

**Issue by liuyao12** [mauriciopoppe/function-plot#116]
Hi Thanks for making this tool! I did a "promotion" for you on observablehq.com (created by Mike Bostock of D3 and others), but if you want to make a more thorough one yourself, I can delete mine.

https://beta.observablehq.com/@liuyao12/function-plot

**Comment by mauriciopoppe** [comment]
thank you very much for the examples! I'll make sure to add this link to the README
