### ISSUE TITLE
Update to D3 V5

### ISSUE THREAD

**Issue by FullPint** [mauriciopoppe/function-plot#117]
With D3 V5 out today, it may be nice to update this package to the current version. I would be more than willing to help or do it on my own.

**Comment by FullPint** [comment]
Sorry -- I've been really busy myself. I think what I'll end up doing is re-writing it to used D3 V5 the best I can this week.

Afterwards if you and I have time available we can discuss what API changes you were thinking about. I haven't used Lerna, is it similar to Yarn Workspaces?

**Comment by kpfromer** [comment]
@FullPint Have you been successful in upgrading the zoom feature? I have had troubles updating the zoom because in v5 there is no `zoom.x().y()`

**Comment by FullPint** [comment]
@kpfromer Sorry I haven't had a real opportunity to work on this for awhile. If you could give me more information I will have time later this week to take a look.
