### ISSUE TITLE
React Component

### ISSUE THREAD

**Issue by FullPint** [mauriciopoppe/function-plot#118]
It may also be nice to spin off an updated version into a React Component. This is something I would be willing to help or work on my own.

**Comment by CharlesFJWilliamson** [comment]
@FullPint Happy to help with this in any way I can.

**Comment by FullPint** [comment]
This week I think I'm going to get this moved up to D3 V5, and then make it a component.

Currently I have a fork with D3 V3 working as an npm dependency, it's easy to throw a component wrapper around it, if you need something working soon.

**Comment by kpfromer** [comment]
I am going to take a shot at this as well. Currently, I am updating the code to es6 and will then try to get d3 v3 up to v5.

**Comment by Arc29** [comment]
Any progress regarding this? I too would love to have a react component for function-plot

**Comment by FullPint** [comment]
@Arc29 unfortunately not long after I made this comment, I had some changes in my availability. Maybe I'll take a stab at it soon but this project's last update was more than 2 years ago.

**Comment by mauriciopoppe** [comment]
I've started working on this project again and it's now using d3 v6 and TypeScript, please check out the releases!

**Comment by mauriciopoppe** [comment]
A simple example of a react component:

```typescript
import React, { useEffect, useRef } from 'react'
import functionPlot, { FunctionPlotOptions } from 'functionPlot'

export interface FunctionPlotProps {
  options?: FunctionPlotOptions
}

export const FunctionPlot: React.FC<FunctionPlotProps> = React.memo(({ options }) => {
  const rootEl = useRef(null)

  useEffect(() => {
    try {
      functionPlot(Object.assign({
        target: rootEl.current
      }, options))
    } catch (e) {}
  })

  return (<div ref={rootEl} />)
}, () => false)
```

Usage:

```
<FunctionPlot options={options}>
```

**Comment by MiltonCobo** [comment]
I also would like very much to have a vueJS component. I think from the react component to the vue component it wouldn't take that long!

**Comment by Jutanium** [comment]
@MiltonCobo Sometime over the next couple weeks I'll be testing out a Vue version of this project. I'll link it here if it's successful.
