### ISSUE TITLE
functionPlot not defined??

### ISSUE THREAD

**Issue by dczk15** [mauriciopoppe/function-plot#119]
hey mauricio,

when attempting to graph an equation using functionPlot( ), i keep getting an error on the console stating "functionPlot is not defined"

have i set up my environment incorrectly? i did import both "function-plot.js" and "d3.js" into my document

**Comment by ziggity** [comment]
I agree - this happened to me as well. Any updates would be greatly appreciated!

**Comment by monstermash2008** [comment]
Same thing happening for me, including the example on the site:
[http://mathjs.org/examples/browser/plot.html.html](url)

**Comment by mauriciopoppe** [comment]
thank you for letting me know, the CDN provider is apparently dead, I'll update both the website and the README with info about the new links like this one

[![Edit function-plot](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/l6k20jrlm)
