### ISSUE TITLE
Scatter graph: how do I increase the radius of the points?

### ISSUE THREAD

**Issue by PHCCorso** [mauriciopoppe/function-plot#127]
The points on the scatter graph are too tiny. Is there any way to increase their radius to make them more visible?

**Comment by PHCCorso** [comment]
Nevermind. I've just got it to work:

```js
	const circles = document.querySelectorAll("g circle");
	circles.forEach((circle) => {
		circle.r.baseVal.value = 3;
		circle.style.opacity = 1;
	});
```

**Comment by minoush82** [comment]
This works as long as you don't zoom in/out, after which the points revert to their tiny size.

**Comment by mauriciopoppe** [comment]
@minoush82 I'm not sure if in the past I overrode the value through CSS, maybe you could try that?
