### ISSUE TITLE
Rerender bug: point lines freeze and stay

### ISSUE THREAD

**Issue by alexgnatrow** [mauriciopoppe/function-plot#128]
After i draw a bunch of point lines, like dozens of them and want to go back to the previous tab, which renders canonical case, it renders, but vectors just freeze and stay.

I can change the scale of main function and all is ok but these vectors just dont go whatever refresh technique I use.
When I render them ony by one, it is completely ok.
<details>
<summary>screenshots</summary>
![screenshot_1](https://user-images.githubusercontent.com/22867443/48312146-6ae77980-e5bb-11e8-8c58-3d77d7007819.jpg)
![screenshot_2](https://user-images.githubusercontent.com/22867443/48312147-6ae77980-e5bb-11e8-9639-96fac1d77c90.jpg)
</details>

you can see the result here: https://alexgnatrow.github.io/math-estimation/
just enter 1 and 0 in first and second column respectively and whatever you want in other and click genereate and calculate

<details>
<summary>Code to calculate points</summary>
<pre>
<code>
function getIntervalVectors(i, isOne) {

    let x = pointEstimations[i],
  range = intervalEstimations[i],
  y;
  if (isOne) y = 1.01 * (1 / (data.sigma * Math.sqrt(2 * Math.PI)));
  else y = ((yMax - 0.1) / data.quantity) * i;
  const vertical = {
   points: [[x, yMax - 0.05], [x, 0]],
   color: "black",
   fnType: "points",
   graphType: "polyline"
  };
  const data2 = {
    points: [[x, y], [range[0], y], [range[1], y]],
    graphType: "scatter",
    fnType: "points",
    color: "blue",
    sampler: "builtIn"
  };
  const horizontal = {
    points: [[range[0], y], [range[1], y]],
    fnType: "points",
    color: "red",
    graphType: "polyline"
  };
  return [vertical, data2, horizontal];
}
</code></pre>
</details>

**Comment by alexgnatrow** [comment]
Hey, it would be kind of really nice to respond.

**Comment by mauriciopoppe** [comment]
hey, sorry for not answering to this thread before, have you tried `data.graphInstance.draw()` or `data.graphInstance.build()`? Those methods are not documented as part of the public API but if I remember correctly those should rebuild the graph from scratch if you have a reference to it

**Comment by alexgnatrow** [comment]
I just managed to clear the innerHTML of content. Worked for my client, I guess.
Anyway, thanks for the response and lib!
