### ISSUE TITLE
Request: do not publish .git folder

### ISSUE THREAD

**Issue by beresmate** [mauriciopoppe/function-plot#131]
Hi! Thank you for function-plot! 

Since 1.19.0 the .git folder is beeing downloaded during installation which makes installing other unrelated modules impossible, npm will complain with EISGIT error code. 

1.18.0 is working fine, it does not download the .git folder (altough it does download an .idea folder, but it does not block anything). Could you please exclude the .git folder from the published version? 

Thank you!

**Comment by mauriciopoppe** [comment]
hey @beresmate, I'm really sorry it took me a really long time to make this simple change, I've added it as part of https://github.com/mauriciopoppe/function-plot/releases/tag/v1.19.2
