### ISSUE TITLE
Labels for functions and points?

### ISSUE THREAD

**Issue by JoseAndresCartuche** [mauriciopoppe/function-plot#138]
Thanks for creating such an awesome library! 
Is there any way to label the functions?
When drawing a function, put a label that indicates the corresponding function. The same for the points, some way of putting the coordinates to that point.
Something similar as is done in Geogebra.
[Geogebra Image](https://i.imgur.com/eeGYUg4.jpg)
How could I do it? Thanks in advance.

**Comment by mauriciopoppe** [comment]
the value returned by calling `functionPlot()` is a JS object with properties that point to the SVG nodes, if you want to add your own objects to the canvas you can use these properties
