### ISSUE TITLE
Irregular line width of function graph 6*x^2-2*x^3

### ISSUE THREAD

**Issue by guckstift** [mauriciopoppe/function-plot#140]
When you plot 6*x^2-2*x^3 you get this:

![image](https://user-images.githubusercontent.com/16594755/69611896-087ae300-102f-11ea-9976-2bc8cbfb4494.png)

The line width gets thicker around the local maximum at x=2

**Comment by mauriciopoppe** [comment]
I'm sorry I didn't look at this before, so this library uses interval arithmetic, for some functions for a given x the output will be a range of possible values, in this example `f(2) = [~7.7, ~8.2]`, probably this function is plotted better with `polyline`, check the docs to change the graph type to polyline
