### ISSUE TITLE
Unable to use a function for the plot

### ISSUE THREAD

**Issue by alex4200** [mauriciopoppe/function-plot#142]
I am trying to use a function for plotting (instead of a string), but it does not work. Here is the code:

    var parameters = {
      target: '#myFunction',
      data: [{
        fn: function(scope) {
          return scope.x;
        },
        color: 'red',
        closed: false
      }],
      grid: true,
      yAxis: {
        domain: [0, 24]
      },
      xAxis: {
        domain: [0, 365]
      }
    };

    function plot() {
      var alpha = 23; // a parameter later taken from a html element and to be used in the function.
      // I need to replace the actual function each time I change parameters later. 
      // This is just a simple example.
      parameters.data[0].fn = function(scope) {
        v = alpha * Math.sin(scope.x / 300);
        console.log(v);
        return v;
      };
      functionPlot(parameters);
    }](url)

and html here:

    <script src="https://d3js.org/d3.v3.min.js"></script>
    <script src="https://mauriciopoppe.github.io/function-plot/js/function-plot.js"></script>

    <body onload="plot();"></body>

but when running this code the only output are many NaN's. Is there a problem with the module, or what am I doing wrong here?

**Comment by mauriciopoppe** [comment]
scope.x is an interval and not a number, check the docs for an example on
how to send your own function

**Comment by alex4200** [comment]
I did check an example ( https://mauriciopoppe.github.io/function-plot/) which I repeat here:

```
functionPlot({
  target: '#built-in-eval-function',
  data: [{
    // force the use of builtIn math
    graphType: 'polyline',
    fn: function (scope) {
      // scope.x = Number
      var x = scope.x
      return x * x
    }
  }, {
 ....
```

To me it looks like you define a function, use 'scope' as argument, and the x value is in `scope.x`, like in the example. 

Maybe the example is incorrect? Or I am misunderstanding something?

Also: Can't you just 'fix' my example to show how it must be done?

**Comment by mauriciopoppe** [comment]
So this example works because there are multiple graphTypes each with its
own evaluator, the ‘polyline’ graphtype uses regular arithmetic while the
default one uses interval arithmetic, add the graphType line as shown in
the example.

**Comment by alex4200** [comment]
Yes that seems to work, thanks a lot!
