### ISSUE TITLE
Bug: Exponential functions not plottable

### ISSUE THREAD

**Issue by finnmglas** [mauriciopoppe/function-plot#143]
Exponential functions like `0.5 * 1.01 ^ x` (of the general type `r ^ x` with `r` being any real number) cause the graph not to display. The point, however, is visible despite that (not in screenshot haha):

![image](https://user-images.githubusercontent.com/40366035/83652540-08016d00-a5bb-11ea-964b-3cedc55c7f18.png)

It would be nice having this fixed ^^

**Comment by mauriciopoppe** [comment]
function-plot uses interval arithmetic by default and the pow function only works with real numbers and not intervals https://mauriciopoppe.github.io/interval-arithmetic/modules/_operations_algebra_.html#pow

To use regular arithmetic please add `graphType: 'polyline'`

https://codesandbox.io/s/function-plot-r48un

**Comment by roblogic** [comment]
Still doesn't work on ObservableHQ... the line is invisible
```
{let target=DOM.element('div')
functionPlot({data:[{fn:'pow(3,x)'}],fnType:'points',graphType:'polyline',target});
return target}
```
