### ISSUE TITLE
Question: Custom Classes

### ISSUE THREAD

**Issue by ruymon** [mauriciopoppe/function-plot#154]
Hi, 

Is there any way to put in custom classes to style for my graph?  To change the the values in CSS like the Background Color; Text Font; Text Size etc.

**Comment by mauriciopoppe** [comment]
Yes, check out the styling section in the homepage https://mauriciopoppe.github.io/function-plot

Also if you want to add more classes on top of what the app has you could do

[![Edit confident-napier-q0nio](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/confident-napier-q0nio?fontsize=14&hidenavigation=1&theme=dark)

**Comment by ruymon** [comment]
Thanks!
