### ISSUE TITLE
ReferenceError: Can't find variable: Element

### ISSUE THREAD

**Issue by kk2dev** [mauriciopoppe/function-plot#158]
I installed d3 version 6 and function-plot using

`npm i d3@6`
`npm install function-plot`

and I am importing function-plot into my react native project like so:

`import functionPlot from "function-plot"`

However', I am getting the error: 

`ReferenceError: Can't find variable: Element`

which seems to originate from polyfills.js in function-plot/dist 

Can you please advise?

**Comment by mauriciopoppe** [comment]
`function-plot` runs wherever the DOM API is available, unfortunately, React Native JS runs in a place where the DOM is not available, you could use a webview https://github.com/react-native-webview/react-native-webview as a workaround

**Comment by kk2dev** [comment]
You mean something like this (?), in the react native code

`<WebView source={require("./components/functionPlotWebview.html")}  />`

where functionPlotWebview.html is something like this: 

```
<!DOCTYPE html>
<html lang="en">
<head>
</head>
<body>
    <p>Hello World<p>
    <script src="https://unpkg.com/function-plot/dist/function-plot.js">
    </script>
    <script>
         functionPlot({
          target: '#quadratic',
          data: [{
            fn: 'x^2'
          }]
        })
    </script>
</body>
</html>
```

That only displays Hello World in my app, nothing else.

**Comment by mauriciopoppe** [comment]
I think you can connect to the webview with Safari in macos to debug the webview, I see that there's no target div, add:

```html
<div id="quadratic"></div>
```

**Comment by kk2dev** [comment]
Thank you, that worked, although the behavior is a bit erratic. I am able to zoom and scroll only once, when I first touch the screen, and then it's not letting me zoom or scroll (although I can still double tap to zoom in, but not out). Do you have any idea why that could be?

**Comment by mauriciopoppe** [comment]
Yes, I worked with React Native and the touch events are captured erroneously because they're going to the native component first and then to the webview contents, this is hard to solve but when I had this problem I added the listeners on the webview and forwarded them to the webview contents i.e. the inner document

**Comment by kk2dev** [comment]
Would you mind elaborating a bit more what you mean? I tried using postMessage and onMessage to communicate a random string from the HTML back to react native, but that did not help. The touch events are still just as erratic, and I can't zoom in and out if I don't do it at the first touch. Here is my code:

```
<WebView
originWhitelist={['*']}
style={{flex: 1, backgroundColor: 'transparent'}}
source={{ html: '<meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0">
          <script src="https://unpkg.com/function-plot/dist/function-plot.js" type="text/javascript"></script>
          <div id="quadratic">
          <script>
                    let contentsBounds = document.body.getBoundingClientRect();
                    let width = 200;let height = 200;let ratio = contentsBounds.width / width;width *= ratio; height *= ratio; 
                    functionPlot({target: "#quadratic",width,height,grid: true,data: [{fn: "x^2",attr: { "stroke-width": 8, id: "id", stroke: "red"}}]}); 
                    window.ReactNativeWebView.postMessage("Empty message")
          </script>
          </div>' }}
scrollEnabled={false}
onMessage={event => {}}
/>

```

**Comment by mauriciopoppe** [comment]
A random event is not going to make it, the event should be the same one that the native component received, i.e. if it's a pinch or a swipe you'd need to forward all of those tiny events to the frame which should also have JS code to understand what it needs to do in that situation.
