### ISSUE TITLE
Graphs visually duplicating other graphs

### ISSUE THREAD

**Issue by Gfellha** [mauriciopoppe/function-plot#159]
Hello, I have a bit of an odd glitch I've been having recently. For some reason, when having multiple graphs, sometimes, the graphs displayed on will, will appear on another graph--but they will not interactable are simply there visually. I have an image of what's going here. Then only one I can itnereact with (such as with the derivative function, and to check points is the one that goes to zero.) i
![glitch](https://user-images.githubusercontent.com/36118564/98447902-888e4180-20f6-11eb-9ec3-29585f2ca26b.PNG)
If I move or drag the screen around, the lines that are there only visually will remain in the same place on the screen, as shown in this picture. 
![glitch2](https://user-images.githubusercontent.com/36118564/98447940-c8552900-20f6-11eb-811d-199f5e2885ed.PNG)

As for reference, I have the graphs listed in a tabulator table, since I need to create them dynamically, since there can be alot of a graphs, or a few, depending on the data inputted. I imagine the glitch is caused by some weird interaction between tabulator, and function-plot, but I don't know for sure.

I figured I'd just post this strange visual glitch here, to let others know, or possibly get a fix if there is one.

Thank you, and have a nice day.

**Comment by mauriciopoppe** [comment]
I think this could happen if the same object is used in multiple function
plot calls, function-plot augments the input object with metadata that’s
used across renders.

**Comment by Gfellha** [comment]
So, by the the same object, for you mean, in the:

`functionPlot({
            width: $("#reportContent").width(),
            height: 500,
            target: root,

            tip: {
                renderer: function () {}
            },
            xAxis: {
                label: "Days",
                domain: [0, 100]
            },
            yAxis: {
                label: "Concentration",
                domain: [0, 150]
            },
            annotations: anno,
            grid: true,
            data: functData
        });`

The functData object that contains the the graphing equations and the like?

**Comment by mauriciopoppe** [comment]
Yes, `functionPlot` modifies both the root object as well as the data object and I'm not sure what would happen if it's used in multiple invocations e.g.

```javascript
const config = {}
functionPlot({ target: '#a', ...config })
functionPlot({ target: '#b', ...config })
```
