### ISSUE TITLE
attr doesn't work

### ISSUE THREAD

**Issue by alexmww** [mauriciopoppe/function-plot#164]
Steps to reproduce:
1. Open codesandbox example https://codesandbox.io/s/muddy-cdn-ibl5x?from-embed=&file=/src/index.tsx
2. Set data as:
```
data: [
    {
      fn: "x^2",
      attr: {
        "stroke-width": 10
      }
    }
  ]
```
3. Nothing happens, attributes didn't get applied.

**Comment by mauriciopoppe** [comment]
Thanks for the report, this should be working in https://github.com/mauriciopoppe/function-plot/releases/tag/v1.22.3, note that this only works with `graphType: 'polyline'`

**Comment by alexmww** [comment]
Thanks for the quick response! 

For graphType: 'polyline' everything works as expected. But is there any reason to leave `attr` functionality only for polyline? 
For example, It would be super handy for graphType: 'scatter' when dealing with graphs with punctured points like in the one below: 
![graph1](https://user-images.githubusercontent.com/32086218/102863107-b213ea00-4464-11eb-990f-f67f42ed6250.png)

Also, I would recommend making `d.attr.hasOwnProperty(k)` check when iterating through an object's keys.

Please, consider https://github.com/mauriciopoppe/function-plot/pull/165

**Comment by mauriciopoppe** [comment]
thanks for the PR! I've released it in https://github.com/mauriciopoppe/function-plot/releases/tag/v1.22.4, this was implemented before and I must have removed it because of the transition to d3 v6

**Comment by alexmww** [comment]
👍
