### ISSUE TITLE
x in exponent causes plot to disappear

### ISSUE THREAD

**Issue by Ginlick** [mauriciopoppe/function-plot#170]
Whenever I put x in the exponent, the plotted line disappears, even for a function as simple as 2^x. Points on the line are still shown.
![BD1C23C6-C97E-4694-8369-06BCF7994D0E](https://user-images.githubusercontent.com/82307311/114295883-671bf200-9aa8-11eb-898f-1856e54ab254.jpeg)

The graph works perfectly fine and no errors are thrown. The path with class="line line-0" is still created, but has no content. 
![9185C575-31D0-4AE9-A778-54AD5AACEE8F_4_5005_c](https://user-images.githubusercontent.com/82307311/114295900-8fa3ec00-9aa8-11eb-9139-ff54ecf311e1.jpeg)

Otherwise, the library works admirably well and looks gorgeous.

**Comment by mauriciopoppe** [comment]
more details at https://github.com/mauriciopoppe/function-plot/issues/143
