### ISSUE TITLE
Does the tool support exponential functions？

### ISSUE THREAD

**Issue by chenwenhang** [mauriciopoppe/function-plot#174]
Thank you for your amazing work!

I have a question, when I try to draw exponential functions like "y(x) = 2^x", it doesn't work.  Does this tool support exponential functions? Or is there something wrong with the way I use it?

```JavaScript
functionPlot({
      target: "#root",
      width: $('#root').width(),
      height: $('#root').width(),
      xAxis: {
          domain:[-10, 10]
      },
      yAxis: {
          domain: [-10, 10]
      },
      grid: true,
      data: {
          fn: "2^x",
      }
});
```

**Comment by mauriciopoppe** [comment]
yes it does, please add `graphType: 'polyline'` to data, related: https://github.com/mauriciopoppe/function-plot/issues/143

**Comment by chenwenhang** [comment]
It does work! Thank you!
