### ISSUE TITLE
Adding object element on top of graph

### ISSUE THREAD

**Issue by bveeni** [mauriciopoppe/function-plot#175]
Hi
I am wondering if there is any way we can add element on top of graph- and synchronization work on
that element as well.
For example- For function-plot of horizontal line-
I want to add one extra object element(for eg: vertical line) on top of the graph (i.e horizontal line) and that moves as well with mouse hover.
I am able to do that if I add that element within the canvas, but here I want to amend this element on top of graph rather than within canvas, so that values attached with  my vertical line can be seen
when it is out of canvas without doing zoom.

So, I want to make both of them visible by amending that line on top of graph.
Also, I want to confirm that in order to make synchronization working on element, does that element need to be inside canvas?
Please let me know any suggestion on this.
Thanks
Binita Shrestha

**Comment by mauriciopoppe** [comment]
> Also, I want to confirm that in order to make synchronization working on element, does that element need to be inside canvas?

It needs to be inside the `svg` element created by function plot however it can be synchronized outside function plot by using its `chart.meta` object and the events fired by the instance, for example:

```
const instance = functionPlot({ })

// create element from the outside
const newCircle = document.createElement('circle')
instance.canvas.appendElement(newCircle)

// subscribe to events emitted by the instance on scale, pan, etc
// https://github.com/mauriciopoppe/function-plot/blob/bc887ca9225bb0bc211bae5f7e50136773bf085a/src/index.ts#L60-L72
instance.on('tip:update', function () {
   // https://github.com/mauriciopoppe/function-plot/blob/bc887ca9225bb0bc211bae5f7e50136773bf085a/src/index.ts#L677-L691
   // TODO: update newCircle based on {x, y, index}
   // TODO: use instance.meta.xScale and instance.meta.yScale too
})

```
