### ISSUE TITLE
Feature request: A simple downloadable example to learn from would be great

### ISSUE THREAD

**Issue by kupietools** [mauriciopoppe/function-plot#180]
I am just trying to pass a simple mathematical function to a javascript library and have it plotted. This project seems like it can do it, the demo page certainly appears to show that, but I've downloaded this package and I can't for the life of me figure out how to accomplish this simple task. 

I don't know what a "tsx" file is, I don't know what a "notebook" is. I can't find anything in here that just shows an html page and javascript that allows a function to be plotted in a browser window. The front end shows it, but when I download your huge demo page with dozens of examples, I can't even begin to figure out what I'm supposed to do to get it to work. And the "site" folder in the repo, which looks like the source of your demo page, doesn't work. 

It would be nice if somewhere in here you just included a simple but complete working example with an HTML page and the necessary javascript and CSS to plot a function.

**Comment by kupietools** [comment]
Never mind, found another js plotting package that includes working setup instructions. Thanks.

**Comment by mauriciopoppe** [comment]
Thank you for the feedback, in the README as well as on the webpage there's a codesandbox link with a usage example, https://codesandbox.io/s/muddy-cdn-ibl5x?fontsize=14&hidenavigation=1&theme=light
