### ISSUE TITLE
Flipping axes

### ISSUE THREAD

**Issue by jannejjj** [mauriciopoppe/function-plot#181]
Hello!

This library is fantastic, and I'm using it as a part of my Bachelor's thesis work this spring. I have one problem however. I have a function that i need to plot, it's given in the form ε = f(σ). However, i would need to plot it so that ε is on the x-axis and σ is on the y-axis. I didn't find anything by looking at the docs, did I miss something or is this just something that cannot be done?

Obviously one way would be to find the inverse of the function, but it's not possible in this case due to the nature of the function.

Thank you so much for your help.

**Visualization**
Current situation:
![image](https://user-images.githubusercontent.com/61980297/152019131-9c75033f-f767-4b6b-8ad5-2725400ad083.png)

Desired situation:
![image](https://user-images.githubusercontent.com/61980297/152019307-326d8699-432d-433f-a0a3-b82900770175.png)

**Comment by mauriciopoppe** [comment]
There might be a way to approximate it by making the function an implicit function e.g. `0 = f(σ) - ε`, there's an example in with an implicit function in the main page

```
functionPlot({
  target: '#implicit-complex',
  yAxis: {domain: [-3.795918366, 3.795918366]},
  xAxis: {domain: [-6, 6]},
  disableZoom: true,
  data: [{
    fn: 'cos(PI * x) - cos(PI * y)',
    fnType: 'implicit'
  }]
})
```

Unfortunately flipping axes is not supported, there's a trick to do it with scales in CSS but also the text would be reversed, please look at this example https://jsfiddle.net/7vg2tn83/1/ and apply it to the root svg element
