### ISSUE TITLE
Lack of documentation

### ISSUE THREAD

**Issue by Mikiyas721** [mauriciopoppe/function-plot#184]
The allowable string that needs to be passed to the 'fn' parameter is not specified. How can I draw square, triangular, sawtooth and pulse waveforms? Also how can I remove the axes and margin?

**Comment by mauriciopoppe** [comment]
This library uses https://github.com/mauriciopoppe/built-in-math-eval and https://github.com/mauriciopoppe/interval-arithmetic-eval for `fn`, the examples supported are in the homepage, by default you can't remove the axes and margin with a configuration, you can modify the DOM objects inside `instance = functionPlot({ ... })` though

**Comment by Mikiyas721** [comment]
Is it possible to draw a graph by providing your library with an array of coordinates?

**Comment by mauriciopoppe** [comment]
There's an example about `Points and polylines` in https://mauriciopoppe.github.io/function-plot/

**Comment by Mikiyas721** [comment]
Thank you. I will check it out.
