### ISSUE TITLE
Could you provide an rest api for  function-plot?

### ISSUE THREAD

**Issue by mokeyish** [mauriciopoppe/function-plot#186]
`function-plot` is a very nice library. 

I want to use it in my markdown note.
similar as:
```md
![](https://math.now.sh?from=y=x^2+3&color=red&alternateColor=cyan)
```
and then will display as:
![](https://math.now.sh?from=y=x^2+3&color=red&alternateColor=cyan)

**Comment by mauriciopoppe** [comment]
Serving a rendered image of a plot goes beyond what function-plot does, I'd suggest embedding an example that you have in an iframe like this:

```
<iframe src="https://codesandbox.io/embed/muddy-cdn-ibl5x?fontsize=14&hidenavigation=1&theme=dark"
     style="width:100%; height:500px; border:0; border-radius: 4px; overflow:hidden;"
     title="muddy-cdn-ibl5x"
     allow="accelerometer; ambient-light-sensor; camera; encrypted-media; geolocation; gyroscope; hid; microphone; midi; payment; usb; vr; xr-spatial-tracking"
     sandbox="allow-forms allow-modals allow-popups allow-presentation allow-same-origin allow-scripts"
   ></iframe>
```

**Comment by mokeyish** [comment]
Github not support iframe embedding.

**Comment by mokeyish** [comment]
Or Intergating `function-plot`  into [mermaid](https://github.com/mermaid-js/mermaid) was better choice. Since It's not easy to add latex in URL, because of the url encoding.


https://math.yish.org/math_plot.html?y=x%5E2%5C%7Bx%3E0%5C%7D;y=%5Csin(x)%5C%7B-3%3Cx%3C3%5C%7D

**Comment by mauriciopoppe** [comment]
@Linho1219 has recently published a very nice webapp that can plot functions using query params in the url at https://plot.linho.cc/. If there's a webpage to image as a service then we could achieve having plots as images.
