### ISSUE TITLE
Maintain zoom/translation after redraw

### ISSUE THREAD

**Issue by adamvanaken** [mauriciopoppe/function-plot#199]
Hi all,

I have a graph that, through various User interactions, redraws itself with different points/colors/lines. My draw code sets the scaleExtent, translateExtend, and domains based on the initial state of the graph.

However, I'm having trouble redrawing and keeping the "viewport" unchanged. I'm using the `all:zoom` event to maintain the current transformation object and use that to calculate new domains/extents on redraw, but it is not working very well.

My math might just be off, but I have to ask: Is there a more straight-forward way to achieve this, perhaps via the underlying D3 instance?

Here is a simple CodeSandbox of my attempt so far: https://codesandbox.io/s/relaxed-voice-scx49j?file=/src/App.js

EDIT: I basically just need to capture the X/Y ranges at any given moment so I can redraw with them

**Comment by adamvanaken** [comment]
Brilliant! Thank you so much! (And just as I started getting the math to work :P)

**Comment by SakiiCode** [comment]
@adamvanaken Can you provide some sample code for this? I can't get this working in React

**Comment by adamvanaken** [comment]
@SakiiCode Just like in the Update example that mauriciopoppe linked, I am simply keeping the Options object around. I specifically rebuild it only if the user hits a "Reset" button.
