### ISSUE TITLE
power is not an integer, you should use nth-root instead, returning an empty interval

### ISSUE THREAD

**Issue by xxwweb** [mauriciopoppe/function-plot#200]
Hi，Your framework has a design flaw. When using the input {fn: ' x ^ (1/2)'}, It cannot be drawing, and warned me. Please tell me how to input  'x ^ (1/2)' correctly, thank you.

**Comment by mauriciopoppe** [comment]
This library uses interval arithmetic by default which makes it hard to do exponentiation, please check out this issue to use the regular math library https://github.com/mauriciopoppe/function-plot/issues/174
