### ISSUE TITLE
Quadratic equation 

### ISSUE THREAD

**Issue by Luckyluke1988** [mauriciopoppe/function-plot#201]
Hello Together.

i hope i am doing the right thing to open a Issue here.

I have a Problem, i cant figure out to get the right Curve in my Graph for this equation.
My Equation looks like this: ax^2+bx+cx the only thing i get to work is x^2+x+x.
Is that even supposed to be possible as a fn Parameter?

What i have:
`
  functionPlot({
      target: '#canvas',
      data: [{
        fn: 'x^2+x+x',
        color: 'blue'
      }],
      grid: true,
      yAxis: {domain: [-10, 10]},
      xAxis: {domain: [-10, 10]}
  })
`
![image](https://user-images.githubusercontent.com/48966827/171202137-6287c474-13c9-4319-94ab-2f425b079aa2.png)

What i want:
`
  functionPlot({
      target: '#canvas',
      data: [{
        fn: 'ax^2+bx+cx',
        color: 'blue'
      }],
      grid: true,
      yAxis: {domain: [-10, 10]},
      xAxis: {domain: [-10, 10]}
  })
`
I think the graph would move a bit to the left, but instead i get an error `CodeGenerator.js:43 Uncaught SyntaxError: symbol "ax" is undefined`
![image](https://user-images.githubusercontent.com/48966827/171202231-69c21a91-dbab-4c8d-a095-8ed3cea7443f.png)

**Comment by mauriciopoppe** [comment]
Additional parameters are sent through the `scope` property, see this example in Observable https://observablehq.com/@mauriciopoppe/function-plot#cell-208 where sliders control the values of `a` and `c`

**Comment by APCAPCAPC** [comment]
I also had the same problem, and the solution i had was instead of "4x" you write "4*x". Otherwise I get the same error as you.

**Comment by Luckyluke1988** [comment]
Thank you guys, it worked.
