### ISSUE TITLE
x^(1/3) Not good

### ISSUE THREAD

**Issue by APCAPCAPC** [mauriciopoppe/function-plot#210]
I was working and when playing with some settings i noticed that when i tried to graph x^(1/3) it didn't draw it properly, as it showed the positive side, but on the negative side nothing was drawn.
Here its the configuration
```
{
    "data": [
        {
            "fn": "x^(1/3)",
            "nSamples": 16000,
            "graphType": "polyline"
        }
    ],
    "xAxis": {
        "domain": [
            -7,
            7
        ]
    }
}
```
This is how it should be:
![image](https://user-images.githubusercontent.com/30719108/187743088-aabdb824-7f65-4c42-9ce9-8add5d06f9c4.png)
And this is what the programm graphed (Note that the straight line and the text where other things not related):
![image](https://user-images.githubusercontent.com/30719108/187742957-12f74dc6-bc01-43d6-befb-9f6d7b8b475f.png)

**Comment by mauriciopoppe** [comment]
Thanks for the bug report! The problem is in the native [`Math.pow` function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/pow#return_value) which returns `NaN` if the base is negative and the exponent is a float number.

To correctly evaluate an expression like there are a few options:
- analyze the arguments in the pow nodes (somehow find out from the inner AST nodes that we have an odd/even root)
- do an approximation

Going for the approximation seems reasonable but it's not trivial to implement:
- I read https://martin.ankerl.com/2007/10/04/optimized-pow-approximation-for-java-and-c-c/ and something in JS similar could be done with https://stackoverflow.com/questions/21280440/converting-two-uint32array-values-to-javascript-number/21282715#21282715

**Comment by APCAPCAPC** [comment]
I have an idea, but i do not know how to implement it. So, having in mind that it calculates the values correctly when the input is positive, we could do something like this:
![image](https://user-images.githubusercontent.com/30719108/197278533-589f14b7-2b06-44c5-bad8-1482a0d4b9c0.png)

Explanation: 

- |x| means the absolute value of x, basicly if
      Enters: positive  Out: positive
      Enters: negative Out: positive
- sign(x) means the sign that has x. For instance, if x is -14, then sign(x) is -1. Like is only the sign.
What all of this is doing is converting the input to positive, calculate the ^(1/3), and then aplying the sign. 

Hope this helps.

**Comment by mauriciopoppe** [comment]
Thanks for the suggestion, I think that the formula depends on the exponent denominator, let's take two examples:

- $x^\frac{1}{2} = \sqrt{x}$ and this is only defined for $x \geq 0$, this happens for every even denominator
- $x^\frac{1}{3} = \sqrt[3]{x}$, it's defined for any rational number $x$, this happens for every odd denominator

As you can see it's a matter of analyzing the denominator if the power is a fraction

**Comment by minhhai2209** [comment]
The definition of exponential function $a^x$ requires that $a$ is positive. I don't think this is a bug. The current plot is correct.

**Comment by APCAPCAPC** [comment]
@minhhai2209 That is a false argument. I will use this as an example:
![image](https://user-images.githubusercontent.com/30719108/199203343-253fb852-7645-4f08-831a-41bd0895ab1a.png)
What this expression does, is search a number, that multiplied by itself 3 times equals to a. Thus, it does not need to always be positive. Lets say that we are finding:
![image](https://user-images.githubusercontent.com/30719108/199203798-316f0069-1b98-499a-b95e-0d88c9858c26.png)
If the 8 was positive, the solution would be 2, as (2)(2)(2) = 8. But, we have a negative number. However, as it isn't even, we can get negative numbers as a result: (-2)(-2)(-2) = -8. And how this all relates to exponents, roots are a representation of exponentials:
![image](https://user-images.githubusercontent.com/30719108/199204708-0623be25-5c58-4df8-835d-106903cff5fc.png)
Thus, in conclusion, what you said, that it needs to be positive, will only be true when the denominator of the exponential is even.

**Comment by APCAPCAPC** [comment]
@minhhai2209 I agree on what you said. So, to solve the problem, we would need to know if the denominator is odd in order to apply the formula i mentioned a few comments ago? 

I will change prespective, as I find easier to work with even numbers. So, what we can do is exactly the opposite: See only if it's even and not apply the formula.

So we are searching numbers that fall in these two categories:
- It has to be even
- It does not have any decimal digits


we could identify any even number just dividing by 2, and if we get a result that has no decimals, it would be an even, and the solution wouldn't be applied. In any other case, that it isn't even, we would apply the solution.

As I said in my other comment, i do not know what tools are available in your framework to make this work. So I don't know how would you implement such a thing.
Hope everything helps.

**Comment by minhhai2209** [comment]
@APCAPCAPC Per the formal definition the function $a^{1/3}$ is different from the function $\sqrt[3]{a}$. What you have written
![image](https://user-images.githubusercontent.com/338700/199220752-9ab593b8-519f-44b2-ae91-410b659b2335.png)
is simply wrong.

More discussion here https://www.researchgate.net/publication/226461615_To_define_or_not_to_define_The_case_of_-813.

The solution to ${-8}^{1/3}$ can only possible using complex numbers.

> @minhhai2209 That is a false argument. I will use this as an example: ![image](https://user-images.githubusercontent.com/30719108/199203343-253fb852-7645-4f08-831a-41bd0895ab1a.png) What this expression does, is search a number, that multiplied by itself 3 times equals to a. Thus, it does not need to always be positive. Lets say that we are finding: ![image](https://user-images.githubusercontent.com/30719108/199203798-316f0069-1b98-499a-b95e-0d88c9858c26.png) If the 8 was positive, the solution would be 2, as (2)(2)(2) = 8. But, we have a negative number. However we can get negative numbers as a result: (-2)(-2)(-2) = -8. This happens because it isn't an even number of multiplications, so the negative signs don't cancel each other out. And how this all relates to exponents, roots are a representation of exponentials: ![image](https://user-images.githubusercontent.com/30719108/199204708-0623be25-5c58-4df8-835d-106903cff5fc.png) Thus, in conclusion, what you said, that it needs to be positive, will only be true when the denominator of the exponential is even.

**Comment by manstie** [comment]
Could you [find all the roots](https://github.com/cortex-js/compute-engine/commit/a70887350b4732723cb952b1e5bb5a464ccb8829#diff-561824f3a308fd74aa68b4f05bece536603969586268d6efe7138762c17ddb16R84-R114) then take the non-complex result?

**Comment by mauriciopoppe** [comment]
Hey guys, after so many months I remembered I already implemented this a long time ago (in 2015 https://github.com/mauriciopoppe/interval-arithmetic/commit/baf57bdce3b327a9aec4b9d5a57be50f0212dba3) 😅. While you can't use `x^(1/3)` a long time ago I implemented a function called `nthRoot` that would render this fine.

```javascript
functionPlot({
  target: '#playground',
  data: [
    {
      fn: 'nthRoot(x, 3)',
    }
  ]
})
```

https://codesandbox.io/p/sandbox/silent-firefly-z8wjp7
