### ISSUE TITLE
Derivative plotting with implicit Fn

### ISSUE THREAD

**Issue by Nurech** [mauriciopoppe/function-plot#213]
How do you insert derivative for  fnType: 'implicit'. I keep getting `Undefined symbol y`.
```javascript
functionPlot({
  target: "#root",
  width,
  height,
  yAxis: { domain: [-10, 10] },
  xAxis: { domain: [-10, 10] },
  grid: true,
  data: [
    { fn: '(y^2)-(x^3-0*x+7)',
    derivative: {
      fn: '(y^2)-(x^3-0*x+7)',
      updateOnMouseMove: true,
      fnType: 'implicit',
    },
    fnType: 'implicit',
  }
  ]
});
```

**Comment by mauriciopoppe** [comment]
Derivative functions are only supported in the polyline graph types, moreover you have to provide the equation after you apply the derivative. Ref https://github.com/mauriciopoppe/function-plot/blob/master/src/helpers/derivative.ts#L69
