### ISSUE TITLE
ERROR Error: implicit is not supported in the `builtIn` sampler

### ISSUE THREAD

**Issue by Nurech** [mauriciopoppe/function-plot#214]
Graph was producing thick line:

![image](https://user-images.githubusercontent.com/20840114/194465045-e543f696-dc45-4aed-baea-cf2a5ad050b6.png)

I tried following advice from https://github.com/mauriciopoppe/function-plot/issues/177 to add `graphType: 'polyline'`.

```javascript
{
      target: '#graph',
      width: 450,
      disableZoom: false,
      yAxis: {domain: [-10, 10]},
      xAxis: {domain: [-10, 10]},
      grid: true,
      data: [
        {
          fn: 'y^2-((x^3)+(-7x)+7)',
          color: '#e7a649',
          fnType: 'implicit',
          graphType: 'polyline'
        },
        {fn: 'x', color: 'pink'}
      ]
    }
```
This results in error.

> ERROR Error: implicit is not supported in the `builtIn` sampler

**Comment by mauriciopoppe** [comment]
This is by design, the implicit sampler only works with interval arithmetic `graphType: 'interval'` and not with `polyline`, ref https://github.com/mauriciopoppe/function-plot/blob/master/src/samplers/interval.ts#L99
