### ISSUE TITLE
maximal number of curves in a graph is limited to 9

### ISSUE THREAD

**Issue by guosheng437** [mauriciopoppe/function-plot#216]
It appears that only up to 9 curves can be plotted in a graph, is there a way to relax this? There is a parameter MaxListeners, however, setting this to a larger number, say MaxListeners=20, does not solve the problem. Freeing up this constraint would make the library more useful, thanks!

**Comment by guosheng437** [comment]
This problem can be seen at:
https://observablehq.com/@liuyao12/function-plot

in the first graph, use the following code:

{
  let target = DOM.element('div');
  functionPlot({
    target,
    xAxis: {domain: [-2, 12]},
    data: [{
      fn: '1+2sin(x)',
      range: [2, 8],
      closed: true
    },
           {fn: '1+x'},
           {fn: '2+x'},
           {fn: '3+x'},
           {fn: '4+x'},
           {fn: '5+x'},
           {fn: '6+x'},
           {fn: 'x-1'},
           {fn: 'x-2'},
           {fn: 'x-3'}
        ]
  })
  return target
}

**Comment by mauriciopoppe** [comment]
Thanks for the bug report, this is fixed in https://github.com/mauriciopoppe/function-plot/releases/tag/v1.23.2
