### ISSUE TITLE
import failed from react component

### ISSUE THREAD

**Issue by omertalmi5** [mauriciopoppe/function-plot#217]
I added function-plot as in docs to react component in next.js project as below
`import functionPlot from 'function-plot'
function Form() {
  const [realRoot, setRealRoot] = useState(0);
  const [imRoot, setImRoot] = useState(0);
  const [showResult, setShowResult] = useState(false);

  functionPlot({
    target: '#plot',
    data: [{
      fn: 'x^2'
    }]
  })`

I got the following error,
![image](https://user-images.githubusercontent.com/43521606/202133126-16f7119c-63a0-46c3-9ef5-cc625874a2b3.png)

What is the cause, I would be glad to add PR for solving it if needed, thanks

**Comment by mauriciopoppe** [comment]
I added some examples that work with React in https://mauriciopoppe.github.io/function-plot/, I didn't test this with next.js though

**Comment by omertalmi5** [comment]
@mauriciopoppe 
It looks like it can't handle with the `require('./polyfills')` in file index.ts file,
how can I test my assumption?

**Comment by mauriciopoppe** [comment]
Thanks for the pointer, I pushed a fix in #222, you could try pulling the latest commit from master to test it

**Comment by mauriciopoppe** [comment]
There's a minimally reproducible example of using function-plot with NextJS in https://github.com/mauriciopoppe/function-plot/issues/278#issuecomment-2008603923 so I think it should be working now with the latest 2.0.0 alpha build.
