### ISSUE TITLE
Few questions regarding the charting options

### ISSUE THREAD

**Issue by sonnyk22** [mauriciopoppe/function-plot#22]
How can I set the following options on the Graph using Function-Plot?
1) Show Axis (toggle on/off)
2) Show Grid (toggle on/off)
3) Show Range (toggle on/off)
4) how to control the Zoom Scale setting?

I cant find any references in the documentation regarding these.

Thanks

**Comment by maurizzzio** [comment]
The only option I coded was about disabling the zoom, most of the stuff listed here can easily be achieved by selecting the svg nodes and doing whatever you want with them

**Comment by maurizzzio** [comment]
Perhaps I'll add a grid/range in the future, seems like a good idea
