### ISSUE TITLE
Plotted Intersections

### ISSUE THREAD

**Issue by sonnyk22** [mauriciopoppe/function-plot#23]
So far this library is doing just about most of the charting related work; a great library.

Is there a way to get the intersection "marked" of the plotted lines when clicked, either on a x,y coordinates close to the intersection, or directly on the intersection.  This is a very important feature and I've seen that most of the plotting web or desktop applications have.  Some go as far as  allowing the end-user to make a region selection on the graph and in turn the graph will selects one intersection in that region. 

On these other applications, all of them are been told first to go into the "intersection mode" by clicking on a button outside of graph, and once the graph has marked the intersection (if any), then it will exit the "intersection mode" on the mouse-up event (or something like that).

Here is one example of it on the FooPlot.com.
![intersection_foo](https://cloud.githubusercontent.com/assets/6744710/9010522/5936faaa-3775-11e5-8f44-3182dfb95042.png)

and here is another one on some other app I've seen:
![intersection](https://cloud.githubusercontent.com/assets/6744710/9010532/67f61bac-3775-11e5-9099-d7ff2d1bc7f1.png)

Here is what I was mentioning before about selecting a region on the graph, and once the mouse is released (mouse-up), the graph will select one intersection; the black vertical lines are the region.
![intersection_region](https://cloud.githubusercontent.com/assets/6744710/9010682/6a6b6d6e-3776-11e5-9f8b-52e2adb7e6af.png)

**Comment by maurizzzio** [comment]
I see, thanks for the feedback the images help a lot. Finding intersections is quite a nice and challenging problem, I see that FooPlot doesn't solve the problem completely check http://fooplot.com/#W3sidHlwZSI6MCwiZXEiOiJ0YW4oeCkiLCJjb2xvciI6IiMwMDAwMDAifSx7InR5cGUiOjAsImVxIjoic2luKGV4cCh4KSkiLCJjb2xvciI6IiMwMDAwMDAifSx7InR5cGUiOjEwMDAsIndpbmRvdyI6WyItMi43MTU2MzI1Mzc0OTk5ODM1IiwiNy42ODQzNjc0NjI0OTk5NjIiLCItMy4wMjQ2OTg3MTg3NDk5ODEiLCIzLjM3NTMwMTI4MTI0OTk3MDMiXSwic2hvd3RpY2tzIjowLCJncmlkY29sb3IiOiIjQ0ZDRkNGIn1d

Right now I'm quite busy and I might implement this in the future, luckily the problem can be solved easily with interval math :smiley:

**Comment by sonnyk22** [comment]
Thanks for getting back to me on this.  I had a feeling this could be a slightly challenging problem to implement, but glad to know that hopefully it can be added as feature hopefully in the near future. Once these new features (#17, #23) are added, this library will be have 100% of the most important features that any developers/companies would ever need to leverage this library, since it has been implemented on top of the powerful D3, thus it will gain a great publicity in the corporate world.

**Comment by sonnyk22** [comment]
The solution to issue #17 is great.  It would be fantastic, if there is a possibility to apply the same Zoom Box (may be with another key 'CTRL') solution to this one to get "one" intersection.
