### ISSUE TITLE
problem with plotting "sin(x)/x"

### ISSUE THREAD

**Issue by DylanXie123** [mauriciopoppe/function-plot#232]
the plot of `sin(x)/x` seems to oscillate around `x=0`
![image](https://github.com/mauriciopoppe/function-plot/assets/29018622/23229116-ef33-4dba-b18b-fbd443a71414)
while the correct plot should be:
![image](https://github.com/mauriciopoppe/function-plot/assets/29018622/d3690a6e-3649-46d1-bb90-d2d7cfcab8ef)

**Comment by mauriciopoppe** [comment]
Thanks for the report, this is a limitation of interval arithmetic when there's a division with a denominator that contains 0, please use `graphType: 'polyline'` to use the normal arithmetic skipping interval arithmetic.
