### ISSUE TITLE
Adding Elements to the Graph

### ISSUE THREAD

**Issue by minoush82** [mauriciopoppe/function-plot#240]
I want to be able to add elements to the generated function plot e.g. a text area. It's been suggested in the thread https://github.com/mauriciopoppe/function-plot/issues/175 to use the following:

```
const instance = functionPlot({ })
// create element from the outside
const newCircle = document.createElement('circle')
instance.canvas.appendElement(newCircle)
```

So I tried that:
```
const instance = functionPlot({  // defining the plot here });
const newCircle = document.createElement('circle');
instance.canvas.appendChild(newCircle);
```

But I get the error:

`Uncaught TypeError: instance.canvas.appendChild is not a function`

Any ideas?

**Comment by mauriciopoppe** [comment]
Ref #175, I think that when that posted function-plot was still using a version of d3 which wasn't modularized, I upgraded functionPlot to use d3 v6 which is modularized but changed the way it works under the hood. If you want to access the canvas element you could do:

```
const instance = functionPlot({ ... })
// the g.canvas group
instance.canvas.enter.node()
```

For additional DOM elements I think they could be outside the root `<svg>` tag, what would be the purpose of adding a textArea to functionPlot? I think that both can coexist in the page but as different controlled components e.g.

```html
<div>
  <!-- controlled by your app -->
  <div class="my-app">
    <textarea />
  </div>
 
  <!-- controlled by function plot -->
  <div class="function-plot-graph">
    <svg />
  </div>
</div>
```

**Comment by minoush82** [comment]
I am still not able to make sense of this. I want to add a label to a given point in the functionplot graph. How can:
```
const instance = functionPlot({ ... })
// the g.canvas group
instance.canvas.enter.node()
```
help me achieve this? Where can I find more information about this?

**Comment by mauriciopoppe** [comment]
Right now there's no API to extend functionPlot besides the default plotters it has however in the past I made plugins and they worked just fine.

You have to imagine that the canvas is not static so any elements you manage to put inside the canvas would also need to be translated/scaled/rotated. In the past I created one plugin that worked with the previous version of d3 (not the latest version) and the [source code is here](https://github.com/mauriciopoppe/function-plot/blob/master/src/plugins/zoom-box.js). As you can see [it subscribes to events emitted by function plot to do rerendering](https://github.com/mauriciopoppe/function-plot/blob/a538ff88c886f85888685e3bc18ae0bb60954f34/src/plugins/zoom-box.js#L66-L73).

**Comment by minoush82** [comment]
Thanks.
