### ISSUE TITLE
zoom:scaleUpdate is not fired

### ISSUE THREAD

**Issue by webdeb** [mauriciopoppe/function-plot#245]
This does not fire
```
instance.on("zoom:scaleUpdate", (x, y) => console.log(x, y))
```

This does
```
instance.on("zoom", (e) => console.log(e))
```

Unfortunately, there is not clear information about the x/y scales. I would like to save the scale data, which were made by the user, and use it to stop automatic scaling when params are changed.

**Comment by webdeb** [comment]
Btw, I am using function-plot as a React Component. So the re-rendering happens when state in data is changed. So the problem is, that after the user has scaled the plot to some point and then changed the params the plot jumps to initial zoom and scale level.

**Comment by webdeb** [comment]
I've modified your react example to not rerender the plot, and pass the options only at initialisation, adding handlers and data in a separate useEffect hook.

```ts
import React, { useEffect, useRef, useState } from "react";
import functionPlot, { FunctionPlotOptions } from "function-plot";

export interface FunctionPlotProps {
  options?: FunctionPlotOptions;
}

export const FunctionPlot: React.FC<FunctionPlotProps & any> = ({
  options,
  data,
  eventHandlers = {},
}) => {
  const rootEl = useRef(null);
  const [plot, setPlot] = useState(null);

  useEffect(() => {
    if (!rootEl.current || plot) return;
    const plotInstance = functionPlot(
      Object.assign({}, options, { target: rootEl.current })
    );
    for (let k in eventHandlers) {
      plotInstance.on(k, (...args) => eventHandlers[k](...args, plotInstance));
    }
    setPlot(plotInstance);
  }, [options, rootEl.current, plot]);

  useEffect(() => {
    if (!plot || !data) return;
    plot.options.data = data;
    plot.draw();
  }, [data, plot]);

  return <div ref={rootEl} />;
};
```

Now I am facing another problem, when switching pages in a next app, it seems that the old instance is still inside memory and effects the new one. Its not part of that issue, but how would you clear the instance effectively from memory in this case. I think there should be somekind of destroy method, which we could call in the return callback of `useEffect` on unmounting.

**Comment by mauriciopoppe** [comment]
Thanks for the hack! So the cache is based on the `id` property that functionPlot sets on startup

https://github.com/mauriciopoppe/function-plot/blob/b2f7f60dfb0c0f88662c986ca496af0f58e652e5/src/index.ts#L788C41-L788C41

A possible destroy function could be:

```javascript
const functionPlotState = {}
functionPlot(functionPlotState)
function destroy() {
  functionPlotState.id = null
}
```

Agreed on the API need, I think a destroy method would definitely help

**Comment by mauriciopoppe** [comment]
Tracking the introduction of a delete API in https://github.com/mauriciopoppe/function-plot/issues/262

**Comment by mauriciopoppe** [comment]
There's a new `destroy` method in the API, you can use that during the useEffect teardown, please check https://github.com/mauriciopoppe/function-plot/issues/262

**Comment by mauriciopoppe** [comment]
For your original question, I believe I didn't implement `zoom:scaleUpdate` although I added it in the docs, I removed a reference from the docs in https://github.com/mauriciopoppe/function-plot/commit/b5f11048d4bf5b8cb06f015f9cd28cc1edc3cde4.
