### ISSUE TITLE
Integration

### ISSUE THREAD

**Issue by rreusser** [mauriciopoppe/function-plot#25]
At a glance since derivatives and shaded regions are already in place, it seemed like a fun and natural extension to add integration. Unfortunately, I started sifting through the derivative code and it wasn't quite as simple as I thought it perhaps might be. I've been working on [a bunch of integration stuff lately](https://github.com/scijs/packages/wiki/Packages#calculus), so at risk of this seeming like a shameless plug, I was wondering if you had thoughts on what it might take to… integrate (punnn) this feature.

In particular, there's not much to it, but the [adaptive simpson's rule method](https://github.com/scijs/integrate-adaptive-simpson) seemed like a possible fit. Just a thought!

**Comment by maurizzzio** [comment]
Thanks for the feedback, [this is the plot](http://requirebin.com/?gist=d2234a42de658c3a219c) for the example given in [integrate-adaptive-simpson](https://github.com/scijs/integrate-adaptive-simpson), how about having a brush [like this one](http://bl.ocks.org/mbostock/1667367) to control the interval of the definite integral or perhaps having the current x-domain values as the interval? is that ok?

**Comment by rreusser** [comment]
Nice. That interval arithmetic looks great! That seems to make some sense. Otherwise I guess you'd specify a fixed range in the config analogous to derivatives.

Also, sorry if the issue suggested that I expected you to do this! I'd be glad to jump in; just thought I'd ask for feedback before getting too far down the wrong path!

**Comment by rreusser** [comment]
Or perhaps the range would only get modified if you clicked on the curve. Otherwise it would pan as usual. That might keep it visually cleaner so that you don't have to duplicate plots just to illustrate an integral, but it may be tricky to override mouse behavior like that.

**Comment by maurizzzio** [comment]
I think the brush would do it, I remember overriding the mouse behavior to create a [zoom-box like plugin](http://requirebin.com/?gist=d2234a42de658c3a219c) which disables the pan/zoom behavior when `shift` is pressed, I think I can do the same for the integral

**Comment by maurizzzio** [comment]
implemented in v1.9
