### ISSUE TITLE
Uncaught TypeError using the React component in Vite

### ISSUE THREAD

**Issue by OmerMessing** [mauriciopoppe/function-plot#250]
Hi, trying to run this in React.

React version: 17.0.0 using Vite.

I installed the latest function-plot (1.23.3) version and this is the error I get:

Uncaught TypeError: Class extends value undefined is not a constructor or null
    at node_modules/function-plot/dist/index.js (index.ts:85:41)
    at __require (chunk-AC2VUBZ6.js?v=66a9f8ec:11:50)
    at index.ts:806:42

This is the component I use:
```
export const FunctionPlot = React.memo(
  ({ options }) => {
    const rootEl = useRef(null);

    console.log(Object.assign({}, options, { target: rootEl.current }));

    useEffect(() => {
      try {
        functionPlot(Object.assign({}, options, { target: rootEl.current }));
      } catch (e) {}
    });

    return <div ref={rootEl} />;
  },
  () => false
);

```

and I rendering it accordingly: 

`   < Graph options={{ data: [ { fn: 'x^2', }, ], }} />`

**Comment by BliemHax** [comment]
Same.

![de257f093f92a79e8346eec7ce68dc1f](https://github.com/mauriciopoppe/function-plot/assets/58077798/c545d848-370a-497f-bd60-5a99f2aadc49)

**Comment by mauriciopoppe** [comment]
Thanks for the report, fixed in https://github.com/mauriciopoppe/function-plot/releases/tag/v1.23.4

I verified that it can be built with Vite in https://stackblitz.com/edit/vitejs-vite-2fffvt?file=index.html
