### ISSUE TITLE
Exporting graph as svg or png

### ISSUE THREAD

**Issue by portna** [mauriciopoppe/function-plot#251]
Hi, enjoying function-plot a lot. Thanks for your work. Question: Is there a way to add a button to export the graph as an svg or png?

**Comment by mauriciopoppe** [comment]
You can do it with JS after it's rendered in the browser, there's a bug open for this in https://github.com/mauriciopoppe/function-plot/issues/246

**Comment by portna** [comment]
Thanks! I will take a look at that.
