### ISSUE TITLE
Labeling points?

### ISSUE THREAD

**Issue by annieetang** [mauriciopoppe/function-plot#253]
Is there a way to label individual points that are generated? I have the coordinates of the points displayed and want to label them "1", "2", etc. 

Thanks for your help!

**Comment by mauriciopoppe** [comment]
Unfortunately no, everything that's rendered is based on the data sent to functionPlot and it only supports the examples in the main docs.

**Comment by mauriciopoppe** [comment]
This is now available at https://github.com/mauriciopoppe/function-plot/releases/tag/v1.24.0. Please check the release notes.

**Comment by annieetang** [comment]
Thank you so much!! I really appreciate it and the quick new feature!
