### ISSUE TITLE
error painting of (6x ^ 5 - 15x ^ 4 + 10x ^ 3) ?

### ISSUE THREAD

**Issue by eczn** [mauriciopoppe/function-plot#263]
<img width="1727" alt="image" src="https://github.com/mauriciopoppe/function-plot/assets/13131724/45b0208d-d8e7-4f8e-8708-8248c4d4f3e1">

**Comment by mauriciopoppe** [comment]
This is a consequence of carrying errors using interval arithmetic which is the default evaluator, please check https://github.com/mauriciopoppe/function-plot/issues/177#issuecomment-1002866152 for more info.

You can use the following to use the builtIn evaluator

```
...
data: [
	{
		fn: '6x ^ 5 - 15x ^ 4 + 10x ^ 3',
		graphType: 'polyline'
	}
]
```
