### ISSUE TITLE
Change requires to import for all d3-shape

### ISSUE THREAD

**Issue by preethamrn** [mauriciopoppe/function-plot#270]
Since d3-shape is now a pure ESM package (from version 3 [onwards](https://github.com/d3/d3-shape/releases/tag/v3.0.0)), importing it using requires gives the error:
```
require() of ES Module node_modules/d3-shape/src/index.js from node_modules/function-plot/dist/chart.js not supported. Instead change the require of index.js in node_modules/function-plot/dist/chart.js to a dynamic import() which is available in all CommonJS modules.
```

**Comment by mauriciopoppe** [comment]
Thanks for the report, fixed in https://github.com/mauriciopoppe/function-plot/pull/271
