### ISSUE TITLE
Setting marks on the graph region

### ISSUE THREAD

**Issue by sonnyk22** [mauriciopoppe/function-plot#28]
This issue is somewhat related to the #26.  Once we get the coordinates from the event in #26, using the “instance” returned from calling the functionPlot() function, is there another function that I call that I can passing in the X and Y coordinates values, so that the FP library can “mark” an X or something similar on anywhere on the graph region and not only be limited to the plotted charts?  Hope this function has a Boolean parameter called “override” so that when it’s set to true, it will clear all the “marks”, and then place the new “mark” based on the new X, Y coordinates.

**Comment by maurizzzio** [comment]
have a look at the homepage and look for the `annotations` example

**Comment by sonnyk22** [comment]
Annotations are great for x or y labeling at the time when graph is getting plotted by calling the functionPlot() function. This marking should take place after the graph has been plotted.  Lets say that the end-user has click on a plotted line, is there and event or a function that we can call so that it can put a mark on the line, as seen below?

![mark](https://cloud.githubusercontent.com/assets/6744710/9188407/df8b64ce-3fa9-11e5-8135-96bbd7fb3227.png)

**Comment by maurizzzio** [comment]
how about using another datum which keeps track of the points? e.g.

```javascript
var options = {
  target: '#demo',
  data: [{
    points: [],
    graphOptions: {
      type: 'scatter',
      sampler: 'builtIn'
    }
  }, {
    fn: 'x^2'
  }]
}
functionPlot(options)
```

And then whenever you get a coordinate just update the `points` option e.g.

```javascript
var x = // some value
var y = // evaluation of a datum with x = some value
options.data[0].points.push([x, y])
functionPlot(options)
```

I haven't tested this, hopefully it works

**Comment by sonnyk22** [comment]
I'll try it first thing tomorrow morning and get back to you.  Thanks

**Comment by sonnyk22** [comment]
I tried your code below on the JS Bin on your site and it worked.

var options = {
  target: '#demo',
  data: [{
    points: [],
    graphOptions: {
      type: 'scatter',
      sampler: 'builtIn'
    }
  }, {
    fn: 'x^2'
  }]
};
functionPlot(options);

var x = 1.367;
var y = 1.870;
options.data[0].points.push([x, y]);
functionPlot(options);

Is there a way to make the mark bigger? like a bigger circle?

**Comment by maurizzzio** [comment]
mmm I think you can override the styling of the <circle> element on your spreadsheet e.g.

```css
.function-plot .graph circle {
  r: 5;
}
```

**Comment by sonnyk22** [comment]
Let me try this right now (CSS style).

**Comment by sonnyk22** [comment]
After a "marking" has been placed on the graph using the code below: 
      options.data[0].points.push([x, y]); functionPlot(options);

the goals I am trying to achieve is that on every click on a plotted line: 
  1) the previous marking should be removed
  2) then a new marking should be displayed (using above code).

how can I clear a "marking" (No 1) once the end-user has clicked on another x, y coordinates on a plotted line?

**Comment by sonnyk22** [comment]
It worked; I was passing in some wrong options.  Based on the code you provided, when clicking on the next coordinates, the previous ones (points: []) gets removed first.  The CSS provided worked great as well.

Thanks

**Comment by meeple142** [comment]
.function-plot .graph circle {
  r: 5;
}

Works in Chrome 48.0.2564.103 m. Not FF 41.0.2 or IE 11.0.9600.18163CO (didn't test others) I think that the idea is that r is a 'physical' property not a style.

See http://stackoverflow.com/a/32410381
So it would be nice if  we could add an r property to the datum just like color. 
Or maybe even just expose all svg attributes. Meaning just check if they are on the datum. I don't know just throwing out an idea.

**Comment by maurizzzio** [comment]
@meeple142 thanks for the info! I'll add this in a future relase
