### ISSUE TITLE
Math-style coordinate system

### ISSUE THREAD

**Issue by dlerb** [mauriciopoppe/function-plot#291]
In a mathematical context (especially in education), coordinate systems are often displayed with the tick marks and tick labels along the x-axis and y-axis (see figure below). As far as I know, there is no out-of-the-box support for this in d3.js, so I do not know how hard it would be to implement this feature, but would be nice to have. It is the main reason why I cannot use this library in mathematics education.

![math-style-coord-lowres](https://github.com/mauriciopoppe/function-plot/assets/89836810/4c897854-8161-46f2-a02f-f4b245a1ddf8)

**Comment by mauriciopoppe** [comment]
This is implemented and released in https://github.com/mauriciopoppe/function-plot/releases/tag/v1.25.0, please check this PR for an example https://github.com/mauriciopoppe/function-plot/pull/295, I'll also add an example to the webpage soon.
