### ISSUE TITLE
How to display the coordinates of points

### ISSUE THREAD

**Issue by qywk99** [mauriciopoppe/function-plot#300]
``` js
functionPlot({
  target: '#points',
  data: [
    {
      points: [
        [1, 1],
        [2, 1],
        [2, 2],
        [1, 2],
        [1, 1]
      ],
      fnType: 'points',
      graphType: 'scatter'
    }
  ]
})
```
like desmos
![image](https://github.com/mauriciopoppe/function-plot/assets/45910487/e4ac47dc-a62f-4366-9df7-97ad01ae1c38)

**Comment by mauriciopoppe** [comment]
You could do it with an additional item in the `data` array:

```
    {
      graphType: 'text',
      location: [1, 1],
      text: 'hello world'
    },
```

There's an example in the webpage https://mauriciopoppe.github.io/function-plot/#text
