### ISSUE TITLE
No option to set plot text color

### ISSUE THREAD

**Issue by NoahK216** [mauriciopoppe/function-plot#307]
There should be an option to set plot text color.

**Comment by mauriciopoppe** [comment]
SVG attributes of an element of `options.data` are customizable through the `attr` option. Graph wide attributes are also customizable through CSS, which part of the graph in particular isn't customizable?

**Comment by NoahK216** [comment]
Yes sorry I should have been more specific. I am having trouble setting the color of the graph title and axis. I have tried to customize this through CSS stylings but I have yet to find a working solution.

Interestingly, with CSS, I am able to set the font-family of the plot text but not color. A working way to modify the title and axis color with CSS would be suitable but I feel an explicit text-color parameter would be better.

**Comment by mauriciopoppe** [comment]
The axis labels are SVG `<text>` so they don't have a color property, use `fill` instead e.g.

```
<text class="x axis-label" text-anchor="end" x="520" y="334" style="fill: red;">x - axis</text>
```
