### ISSUE TITLE
Getting info of which plotted line clicked on

### ISSUE THREAD

**Issue by sonnyk22** [mauriciopoppe/function-plot#31]
Let assume i have a multi-plots graph.  Now if I click on the first plotted line (cos(x)), how can I get the detailed of which plotted line it has been clicked on?

**Comment by maurizzzio** [comment]
the graph doesn't have a `click` event however you can trigger the `mousemove` event with the click coordinates and the instance will fire the `tip:update` event (see the README) whose callback params are `x`, `f(x)` (of the function who has the tip) and the index of the datum
