### ISSUE TITLE
Implicit functions cannot be drawn with type: 'line' or sampler: 'builtIn'

### ISSUE THREAD

**Issue by Frodojj** [mauriciopoppe/function-plot#42]
Attempting to plot the following gives me an error:

``` javascript
    var vv = {
        target: target,
        data: [{
            fn: 'x * x + y * y - 1',
            implicit: true,
            graphOptions: {
                sampler: 'builtIn',
                type: 'line'
            }
        }]
    };
```

The error is `Undefined symbol y`. Removing BOTH graphOptions works, but I need to use math.js so that's not an option for me.

**Comment by maurizzzio** [comment]
The problem is that implicit equations need evaluation for all the points that belong to the viewport, using interval arithmetic (the default option) uses a quadtree to selectively analyze certain parts of the viewport

This cannot be done with math.js yet
