### ISSUE TITLE
Displaying coordinates for Polar and Parametric plots

### ISSUE THREAD

**Issue by sonnyk22** [mauriciopoppe/function-plot#43]
Is there an option to turn on displaying the coordinates on Polar and Parametric plots as well? Either as a single graph or in a multi-graph?

Currently, these coordinates are only displayed on a Function graph, as seen below.

![calc1](https://cloud.githubusercontent.com/assets/6744710/11313288/c000dc1a-8fa9-11e5-8b92-b0f32329de65.png)

**Comment by maurizzzio** [comment]
showing the coordinates for polar/parametric plots is kinda tricky, I'll see if I come up with a good algorithm to solve it

**Comment by sonnyk22** [comment]
I can just imagine the difficulty of the algorithms involved of this feature.  Even getting some coordinates to display would be a fantastic.

**Comment by sonnyk22** [comment]
It would be awesome if this feature could be added to Function-Plot to display the coordinates for Polar/Parametric charts as the way it is currently showing for Functions.
