### ISSUE TITLE
Plot data provided by user in scatter plot

### ISSUE THREAD

**Issue by namrataghadi** [mauriciopoppe/function-plot#66]
Hello,

I am using the points functiontype. I want the Array to be from a variable passed to script. Is there a way to do that?

**Comment by maurizzzio** [comment]
Well you can always do that by calling a function that renders the graph, I don't know how you get your data but once you have it you can do the following

```js
var config = {
  target: '#demo',
  data: [{
    points: [],
    fnType: 'points',
    graphType: 'scatter'
  }]
}

function plot(points) { 
   config.data[0].points = points
   functionPlot(config)
}
```
