### ISSUE TITLE
default graph view with appropriate domain/range

### ISSUE THREAD

**Issue by evykassirer** [mauriciopoppe/function-plot#77]
If you google `x^2 + 10`, the default graph shown has a scale chosen for the axes such that the shape of the graph is pretty clear. 

It seems like `function-plot` always has the same domain/range unless otherwise specified. (x = [-6,6], y=[-4,4], graph centred around the origin). Is there an feature to always make sure the plotted line is visible?

Otherwise looking pretty sweet and fitting my needs - love this library :)

**Comment by maurizzzio** [comment]
Thanks for reaching out, sadly this is not implemented yet. I'd love to implement this feature though, however, I don't have enough time right now (I'm in the process of moving out).

If you want to do this on your own https://www.cs.uic.edu/~wilkinson/Publications/plotfunc.pdf has all the answers!

**Comment by maurizzzio** [comment]
I forgot to mention that you can change the default domains with:

```js
functionPlot({
  xAxis: { domain: [-6, 6] },
  yAxis: { domain: [-4, 4] }
})
```

**Comment by evykassirer** [comment]
Sweet - I might implement that depending on the priorities for my project. Will get back to you!

And thanks for replying so quickly and with the paper with the answers and everything!
