### ISSUE TITLE
Support for non global d3

### ISSUE THREAD

**Issue by QuentinRoy** [mauriciopoppe/function-plot#78]
When using d3 from a bundler such as webpack, d3 is not put into window (which is better).
However, function-plot surprisingly does not support this.

**Comment by maurizzzio** [comment]
Yep, using [browserify-shim](https://www.npmjs.com/package/browserify-shim) is still on my todo list for this project, I'll add it on the next release

**Comment by mauriciopoppe** [comment]
After so many years I've finally migrated to v6, check v1.20.0
