### ISSUE TITLE
mouse tooltip for scatter

### ISSUE THREAD

**Issue by bitjaru** [mauriciopoppe/function-plot#84]
hi.
I want to add the tooltip for scatter also as like linear's.
How can I activate the tooltip to scatter pointer.

**Comment by Marswiz** [comment]
I am enchantering the same problem nowadays, waiting for solution.


发自 网易邮箱大师
On 11/02/2016 13:57, bitjaru wrote:

hi.
I want to add the tooltip for scatter also as like linear's.
How can I activate the tooltip to scatter pointer.

**Comment by maurizzzio** [comment]
Hi and sorry for the really late response! That feature is only implemented for linear functions, unfortunately I'm kinda busy with other stuff and I'm unable to work on this feature

**Comment by dangom** [comment]
How hard is it to implement this feature for someone new to d3?
What would have to be done?

**Comment by maurizzzio** [comment]
The tooltip is disabled intentionally for other graph types as seen here: https://github.com/maurizzzio/function-plot/blob/master/lib/tip.js#L98-L100

What I'd do for scatter is find the closest sample to the mouse position and show the tooltip for that sample if the distance is close enough to some threshold, that's what I did for closed graphs https://github.com/maurizzzio/function-plot/blob/master/lib/tip.js#L117-L138
