### ISSUE TITLE
Invalid byte sequence in UTF-8 (ArgumentError)

### ISSUE THREAD

**Issue by pezzullig** [mauriciopoppe/function-plot#96]
Function plotter works fine locally, then when i deploy to AWS i get this error
```
Result:
  + /opt/elasticbeanstalk/containerfiles/ebnode.py --action node-install
[2017-07-02T10:11:55.288Z] INFO  [26516] - [Application update app-5688f-170702_101145@108/AppDeployStage0/AppDeployPreHook/50npm.sh] : Starting activity...
[2017-07-02T10:13:38.959Z] INFO  [26516] - [Application update app-5688f-170702_101145@108/AppDeployStage0/AppDeployPreHook/50npm.sh] : Activity has unexpected exception, because: invalid byte sequence in UTF-8 (ArgumentError)
```
It seems that when it runs npm install it can't install the function plot package. 
I've checked without the package and it runs fine. 
Not sure what to do here, any way to read the plotter in UTF-8, is that possible? not really sure what that means,
I would really appreciate some help

**Comment by mauriciopoppe** [comment]
could you point to a specific github commit instead? I've recently renamed my github account and that may be causing the problem

e.g.

```json
{
  "dependencies": {
    "function-plot": "mauriciopoppe/function-plot#f978f195fe"
  }
}
```

**Comment by pezzullig** [comment]
Yeah sure, 
the version i have is ```     "function-plot": "^1.17.3",
```
ive found the gitHead to be 
```  "gitHead": "ba7dd686cd47dbf484786b88fc857a6fb8cb2de0",
``` 
Which seems to be the commit just after v1.17.3, 
I hope this helps

**Comment by pezzullig** [comment]
AAh all good! turns out it elastic beanstalk was running 6.10.0 of node, so i upgraded to 7.6.0 and it worked!
